### ISSUE TITLE
Cropped filesize bigger than original

### ISSUE THREAD

**Issue by dgergo** [mdz-repos/mr-image-resize#7]
Hi!

I am a huge fan of your script, thank you for your work! I just have one question, the resized images' file size are usually bigger than the original image.

I upload a 107 kb image (dimensions: 660x327) and a resized and cropped image results in a 400kb file (dim: 566x377, yes slightly higher).

Is there any way I can alter like image quality to ensure that the file sizes could be smaller? I have 17 images on my homepage and images take up to 2,5-3 megabytes out of the total 4.

Thank you in advance!

**Comment by mendezcode** [comment]
Hey! I'm a bit late to the party, sorry about that!

@dgergo I think this has to do with how WordPress works behind the scenes, since the code basically uses the WordPress internal image processing functions. It is actually possible for the output file size to be larger than the input file size.
